### ISSUE TITLE
About psiblast running time is too long

### ISSUE THREAD

**Issue by lvguofeng1303** [mircare/Porter5#11]
I read your paper and found that you need to run psiblast to get the pssm matrix of the amino acid sequence. I also use psiblast to run under the NR database. It takes 1 hour for an amino acid sequence. Why is your psiblast so fast? Is my problem？ my command line is：
`psiblast -query test.fasta -db ./blast/db/nr/nr -num_threads 10 -out_ascii_pssm test.pssm -num_iterations 3 -evalue 0.001`

**Comment by mircare** [comment]
Hi @lvguofeng1303 , I am glad you find one of my papers of interest. I typically use UniRef90, i.e. a redundancy reduced version of the Uniprot databank https://www.uniprot.org/. UniRef90 is considerably smaller than the NR database. Also, I don't need the PSSM as I encode the MSA using our weighting scheme https://www.nature.com/articles/s41598-019-48786-x#Sec16.

Since this is not an issue related to this repository, just drop me an email if you have further questions.

**Comment by lvguofeng1303** [comment]
Hi Torrisi：
	Thank you for your reply！I am still reading your paper and I look forward to communicating with you more in the future. I have a question about the long running time of psi-blast. Recently, I hope to add the pssm matrix of protein sequence to my research, but I suffer from the long running time of psi-blast. It takes about one hour for a sequence on the NR database. . I want to ask you, how long does it take to run psi-blast on the UniRef90 database? And do you think my running time is reasonable, or where is the problem?
